"""Knowledge graph schema declarations."""

from __future__ import annotations

from enum import Enum


class PathPattern(str, Enum):
    """Supported fixed path pattern identifiers."""

    PATIENT_TASKSET_TASK_GAME_TASK_TASKSET_PATIENT = (
        "PATIENT_TASKSET_TASK_GAME_TASK_TASKSET_PATIENT"
    )
    PATIENT_TASKSET_DISEASE_TASKSET_PATIENT = (
        "PATIENT_TASKSET_DISEASE_TASKSET_PATIENT"
    )
    PATIENT_TASKSET_SYMPTOM_TASKSET_PATIENT = (
        "PATIENT_TASKSET_SYMPTOM_TASKSET_PATIENT"
    )
    PATIENT_TASKSET_UNKNOWN_TASKSET_PATIENT = (
        "PATIENT_TASKSET_UNKNOWN_TASKSET_PATIENT"
    )
    DISEASE_TASKSET_PATIENT = "DISEASE_TASKSET_PATIENT"
    SYMPTOM_TASKSET_PATIENT = "SYMPTOM_TASKSET_PATIENT"
    UNKNOWN_TASKSET_PATIENT = "UNKNOWN_TASKSET_PATIENT"


PATIENT_TASKSET_TASK_GAME_TASK_TASKSET_PATIENT = (
    PathPattern.PATIENT_TASKSET_TASK_GAME_TASK_TASKSET_PATIENT.value
)
PATIENT_TASKSET_DISEASE_TASKSET_PATIENT = (
    PathPattern.PATIENT_TASKSET_DISEASE_TASKSET_PATIENT.value
)
PATIENT_TASKSET_SYMPTOM_TASKSET_PATIENT = (
    PathPattern.PATIENT_TASKSET_SYMPTOM_TASKSET_PATIENT.value
)
PATIENT_TASKSET_UNKNOWN_TASKSET_PATIENT = (
    PathPattern.PATIENT_TASKSET_UNKNOWN_TASKSET_PATIENT.value
)
DISEASE_TASKSET_PATIENT = PathPattern.DISEASE_TASKSET_PATIENT.value
SYMPTOM_TASKSET_PATIENT = PathPattern.SYMPTOM_TASKSET_PATIENT.value
UNKNOWN_TASKSET_PATIENT = PathPattern.UNKNOWN_TASKSET_PATIENT.value
