"""Batch direct-entity predictions from exported non-KG patient profile JSONL."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
for candidate in (PROJECT_ROOT, SRC_ROOT):
    candidate_str = str(candidate)
    if candidate_str not in sys.path:
        sys.path.insert(0, candidate_str)

from scripts.predict_training_tasks_from_direct_entity import (  # noqa: E402
    DEFAULT_CONFIG_PATH,
    DEFAULT_SCORED_OUTPUT_DIR,
    predict_training_tasks_from_direct_entity,
    summarize_prediction_result,
)
from similar_user.utils.logger import get_logger  # noqa: E402


LOGGER = get_logger(__name__)
DEFAULT_PROFILE_PATH = Path(
    "data/direct_entity_inputs/base_2026-05-25/"
    "inactive_patient_profiles_2026-05-25.jsonl"
)
DEFAULT_OUTPUT_DIR = Path("data/direct_entity_predictions")


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Run direct-entity predictions from profile JSONL."
    )
    parser.add_argument(
        "--profiles",
        default=str(DEFAULT_PROFILE_PATH),
        help="Profile JSONL generated by export_inactive_patient_profiles.py.",
    )
    parser.add_argument("--config", default=str(DEFAULT_CONFIG_PATH))
    parser.add_argument(
        "--scored-paths-dir",
        default=str(DEFAULT_SCORED_OUTPUT_DIR),
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
    )
    parser.add_argument("--limit", type=int)
    parser.add_argument(
        "--patient-id",
        action="append",
        default=[],
        help="Optional patient ID filter. Can be supplied multiple times.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Skip the LLM call and return deterministic predictions.",
    )
    parser.add_argument(
        "--output-level",
        choices=("ids", "scores", "full"),
        default="scores",
    )
    return parser.parse_args()


def predict_training_tasks_from_profiles(
    *,
    profiles_path: str | Path = DEFAULT_PROFILE_PATH,
    config_path: str | Path = DEFAULT_CONFIG_PATH,
    scored_paths_dir: str | Path = DEFAULT_SCORED_OUTPUT_DIR,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    limit: int | None = None,
    patient_ids: list[str] | None = None,
    use_llm: bool = True,
    output_level: str = "scores",
) -> dict[str, Any]:
    """Run non-patient predictions for records in a profile JSONL file."""
    profiles = load_profiles(profiles_path)
    requested_patient_ids = {str(patient_id).strip() for patient_id in patient_ids or []}
    if requested_patient_ids:
        profiles = [
            profile
            for profile in profiles
            if str(profile.get("patient_id") or "").strip() in requested_patient_ids
        ]
    if limit is not None:
        profiles = profiles[:limit]

    resolved_output_dir = Path(output_dir)
    details_path = resolved_output_dir / "direct_entity_profile_predictions_details.jsonl"
    summary_path = resolved_output_dir / "direct_entity_profile_predictions_summary.json"
    results = []
    errors = []

    for index, profile in enumerate(profiles, start=1):
        patient_id = str(profile.get("patient_id") or "").strip()
        LOGGER.info(
            "Predicting direct entity tasks from profile: progress=%s/%s, patient_id=%s",
            index,
            len(profiles),
            patient_id,
        )
        try:
            result = predict_training_tasks_from_direct_entity(
                patient_id=patient_id,
                base_date=str(profile.get("base_date") or ""),
                age=profile.get("age"),
                education=str(profile.get("education") or ""),
                gender=str(profile.get("gender") or ""),
                disease_names=[
                    str(name)
                    for name in profile.get("disease_names") or []
                    if str(name).strip()
                ],
                config_path=config_path,
                scored_paths_dir=scored_paths_dir,
                use_llm=use_llm,
            )
            results.append(
                {
                    "patient_id": patient_id,
                    "profile": profile,
                    "result": summarize_prediction_result(
                        result,
                        output_level=output_level,
                    ),
                    "full_result": result if output_level == "full" else None,
                }
            )
        except Exception as exc:
            LOGGER.exception("Profile prediction failed: patient_id=%s", patient_id)
            errors.append(
                {
                    "patient_id": patient_id,
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                    "profile": profile,
                }
            )

    write_jsonl_atomic(details_path, results + errors)
    summary = {
        "profiles_path": str(profiles_path),
        "output_level": output_level,
        "requested_count": len(profiles),
        "success_count": len(results),
        "error_count": len(errors),
        "details_path": str(details_path),
        "errors": errors,
    }
    write_json_atomic(summary_path, summary)
    summary["summary_path"] = str(summary_path)
    LOGGER.info(json.dumps(summary, ensure_ascii=False, indent=2, default=str))
    return summary


def load_profiles(path: str | Path) -> list[dict[str, Any]]:
    """Load profile JSONL records."""
    profiles = []
    for line_number, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), start=1):
        text = line.strip()
        if not text:
            continue
        value = json.loads(text)
        if not isinstance(value, dict):
            raise ValueError(f"profile JSONL line {line_number} must be a mapping.")
        profiles.append(value)
    return profiles


def write_jsonl_atomic(path: Path, records: list[dict[str, Any]]) -> None:
    """Write JSONL atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f"{path.stem}.",
        suffix=".tmp",
        delete=False,
    ) as temp_file:
        for record in records:
            temp_file.write(json.dumps(record, ensure_ascii=False, default=str))
            temp_file.write("\n")
        temp_path = Path(temp_file.name)
    os.replace(temp_path, path)


def write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
    """Write JSON atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f"{path.stem}.",
        suffix=".tmp",
        delete=False,
    ) as temp_file:
        json.dump(payload, temp_file, ensure_ascii=False, indent=2, default=str)
        temp_path = Path(temp_file.name)
    os.replace(temp_path, path)


def main() -> int:
    """Run batch profile predictions."""
    args = parse_args()
    try:
        predict_training_tasks_from_profiles(
            profiles_path=args.profiles,
            config_path=args.config,
            scored_paths_dir=args.scored_paths_dir,
            output_dir=args.output_dir,
            limit=args.limit,
            patient_ids=args.patient_id,
            use_llm=not args.dry_run,
            output_level=args.output_level,
        )
    except Exception as exc:
        LOGGER.exception("Profile prediction batch failed: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
